#cloud-config
package_update: true
package_upgrade: true
groups:
  - docker
users:
  - default
  - name: gitlab
    gecos: GitLab
    primary_group: gitlab
    groups: docker, users, admin
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_pub_key1}
      - ${ssh_pub_key2}
timezone: ${timezone}
packages:
  - nano
  - iputils-ping
  - cron
write_files:
  - content: |
      ${docker_compose_content}
    encoding: base64
    path: /home/gitlab/docker-compose.yml
    owner: gitlab:gitlab
    permissions: '0660'
    defer: true
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --authkey ${tailscale_key}
  - mkdir -p ${gitlab_home}/config ${gitlab_home}/logs ${gitlab_home}/data ${gitlab_home}/runner/config
  - chown -R gitlab:gitlab ${gitlab_home}
  - docker compose -f /home/gitlab/docker-compose.yml up -d