networks:
  gitlab-net:
    name: gitlab-net
    driver: bridge

services:
  gitlab:
    image: gitlab/gitlab-ce:18.9.2-ce.0
    container_name: gitlab
    restart: unless-stopped
    networks:
      - gitlab-net
    hostname: ${gitlab_hostname}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Configuração do URL externo do GitLab
        external_url 'http://${gitlab_hostname}'
        
        # Configuração da porta SSH customizada
        gitlab_rails['gitlab_shell_ssh_port'] = ${gitlab_porta_ssh}
        
        # Configuração do Container Registry
        registry_external_url 'http://${gitlab_hostname}:5050'
        gitlab_rails['registry_enabled'] = true
    ports:
      - 80:80
      - 443:443
      - ${gitlab_porta_ssh}:22
      - 5050:5050
    volumes:
      - ${gitlab_home}/config:/etc/gitlab
      - ${gitlab_home}/logs:/var/log/gitlab
      - ${gitlab_home}/data:/var/opt/gitlab
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:v18.9.0
    container_name: gitlab-runner
    restart: unless-stopped
    networks:
      - gitlab-net
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${gitlab_home}/runner/config:/etc/gitlab-runner